### ISSUE TITLE
skt/ko-gpt-trainity  성능 이슈

### ISSUE THREAD

**Issue by Ronalmoo** [Ronalmoo/fewshot_torch#1]
https://huggingface.co/skt/ko-gpt-trinity-1.2B-v0.5

accuracy 결과가 0.0016..
@Taekyoon

**Comment by Taekyoon** [comment]
먼저 확인해 볼 내용은

- 생성한 결과 텍스트로 확인해보기
- 퓨샷 예시 작성엔 문제가 없었는지
- 인덱스가 잘못되진 않았는지 

3개로 나눠서 봐야할 것 같습니다. 저도 한번 디버깅 해봐야겠네요 ㅎㅎ
