### ISSUE TITLE
실험결과

### ISSUE THREAD

**Issue by Ronalmoo** [Ronalmoo/fewshot_torch#3]
<img width="640" alt="image" src="https://user-images.githubusercontent.com/44221520/160656321-a33251c1-e938-4fc7-b6d6-dfe1c206a87c.png">

kakao gpt3 0.595

skt/trinity 0.33

skt/kogpt2 0.0......

**Comment by Taekyoon** [comment]
실험한 prompt 케이스 별로 성능이 어떻게 나왔는지 정리해보면 어떨까요?

**Comment by Ronalmoo** [comment]
좋습니다!

**Comment by Ronalmoo** [comment]
'########\n\n\n' new line 하나 더 추가했더니 0.76까지 오르네요 ㅋㅋ

**Comment by Ronalmoo** [comment]
<img width="611" alt="image" src="https://user-images.githubusercontent.com/44221520/160876464-622e9090-8911-430f-b5e0-f65957f65bf6.png">

=> 0.79

**Comment by Ronalmoo** [comment]
<img width="565" alt="image" src="https://user-images.githubusercontent.com/44221520/160877402-1b62c18b-04ea-4c05-9ea3-df545f4eb9f3.png">
<img width="575" alt="image" src="https://user-images.githubusercontent.com/44221520/160877462-f3c8c25d-a298-4dee-ac03-f9394a3b618c.png">

**Comment by Ronalmoo** [comment]
문과적 소양으로 갑자기 0.2 증가

**Comment by Ronalmoo** [comment]
<img width="577" alt="image" src="https://user-images.githubusercontent.com/44221520/160996604-10e6055d-7a71-4d54-a8c4-08a9a2838b22.png">

huggingface로 변경

**Comment by Ronalmoo** [comment]
<img width="677" alt="image" src="https://user-images.githubusercontent.com/44221520/161435435-0d377f41-98ed-4325-9378-d8003e364bd0.png">
testset 전체 50,000개에 대한 결과

**Comment by Ronalmoo** [comment]
<img width="353" alt="image" src="https://user-images.githubusercontent.com/44221520/161435510-eb800a4d-b9d8-405f-9cd4-047315c0bd68.png">
test_size1000개 , 30개 example
